# Generated by Django 6.0.5 on 2026-05-21 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={},
        ),
        migrations.RemoveField(
            model_name="sale",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="status",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="updated_at",
        ),
        migrations.AlterModelTable(
            name="sale",
            table=None,
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
